version: '3.8'  # Specify the Docker Compose version

services:
  shiny:
    build:
      # Build context is the current directory - relative to docker-compose.yml
      context: ../..
      # Dockerfile to use for building the Shiny app
      dockerfile: ./inst/deploy_app/DockerfileLinode
    ports:
      # Map port 3838 of the host to port 3838 of the container
      - "3838:3838"
    volumes:
      # Volume for Shiny server logs
      - /home/log/shiny-server/:/var/log/shiny-server/
    environment:
      # Example environment variable
      - ENV_VAR=value

  nginx:
    # Use the latest Nginx image from Docker Hub
    image: nginx:latest
    ports:
      # Map port 80 of the host to port 80 of the container
      - "80:80"
    volumes:
      # Mount the custom Nginx configuration
      - /home/unmet-needs/inst/deploy_app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # Nginx depends on the Shiny service
      - shiny
# docker compose up --build
# docker compose -f ./inst/deploy_app/docker-compose.yml -p unmetneeds up --build
# http://139.162.233.246:3838/unmetneeds/
